import { createRequire } from "node:module";
import type { CoreModule } from "./core.js";

const require = createRequire(import.meta.url);

/** wasm core (nodejs target, loaded synchronously). Generated by `npm run build:core`. */
export function loadCore(): CoreModule {
  return require("../core/node/sahou_core.js") as CoreModule;
}
