/* sahou C ABI — generated by cbindgen from core/src/cffi.rs. Do not edit by hand. */

#ifndef SAHOU_H
#define SAHOU_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#if defined(SAHOU_CAPI)
/**
 * Opaque runtime handle over a loaded descriptor. Wraps the same core the wasm/PyO3 runtimes use.
 */
typedef struct SahouRuntime SahouRuntime;
#endif

typedef struct SahouRuntime SahouRuntime;

#if defined(SAHOU_CAPI)
/**
 * Validate a contract (`schema.sahou.yaml` text). Returns a heap JSON string
 * `{"ok":true,"diags":[]}` | `{"ok":false,"diags":[{code,path,message},...]}`.
 * The caller must release the result with `sahou_free`.
 *
 * # Safety
 * `yaml` must be null or a valid NUL-terminated C string.
 */
char *sahou_validate_schema(const char *yaml);
#endif

#if defined(SAHOU_CAPI)
/**
 * Free a string returned by any `sahou_*` function. Passing null is a no-op.
 *
 * # Safety
 * `s` must be null or a pointer previously returned by a `sahou_*` function and not yet freed.
 */
void sahou_free(char *s);
#endif

#if defined(SAHOU_CAPI)
/**
 * Load a descriptor (the text of `gen/descriptor.json`) into a runtime handle. Returns null if the
 * descriptor is invalid. Release with `sahou_runtime_free`.
 *
 * # Safety
 * `descriptor_json` must be null or a valid NUL-terminated C string.
 */
SahouRuntime *sahou_runtime_new(const char *descriptor_json);
#endif

#if defined(SAHOU_CAPI)
/**
 * Free a runtime handle from `sahou_runtime_new`. Passing null is a no-op.
 *
 * # Safety
 * `handle` must be null or a handle from `sahou_runtime_new` that has not been freed.
 */
void sahou_runtime_free(SahouRuntime *handle);
#endif

#if defined(SAHOU_CAPI)
/**
 * List the nodes that can publish (are the `from` of a pub_sub connection), for a sender-node
 * selector. Returns a heap JSON string array `["node",...]` (empty on a null handle / panic).
 * Free with `sahou_free`.
 *
 * # Safety
 * `handle` is null or a live runtime from `sahou_runtime_new`.
 */
char *sahou_node_list(SahouRuntime *handle);
#endif

#if defined(SAHOU_CAPI)
/**
 * List the pub_sub connections `node` can publish on, for a connection selector. Returns a heap
 * JSON string array `["conn",...]` (empty for a null handle / unknown node). Free with `sahou_free`.
 *
 * # Safety
 * `handle` is null or a live runtime; `node` is null or a valid NUL-terminated C string.
 */
char *sahou_connections_from(SahouRuntime *handle,
                             const char *node);
#endif

#if defined(SAHOU_CAPI)
/**
 * Payload schema of `conn` as display rows, for a "what should I send?" panel. Returns a heap JSON
 * array of `[name, type, required, detail]` string rows: `[["x","float","yes","0..1"],...]`
 * (empty array for a null handle / unknown / any-typed connection). Free with `sahou_free`.
 *
 * # Safety
 * `handle` is null or a live runtime; `conn` is null or a valid NUL-terminated C string.
 */
char *sahou_connection_fields(SahouRuntime *handle, const char *conn);
#endif

#if defined(SAHOU_CAPI)
/**
 * Generate a valid sample payload for `conn`'s pub_sub payload (IR-typed), for a "Test send".
 * Returns a heap JSON object string (`{}` for a null handle / unknown / any-typed connection).
 * Deterministic (the core has no randomness). Free with `sahou_free`.
 *
 * # Safety
 * `handle` is null or a live runtime; `conn` is null or a valid NUL-terminated C string.
 */
char *sahou_sample(SahouRuntime *handle, const char *conn);
#endif

#if defined(SAHOU_CAPI)
/**
 * pub_sub send boundary (TouchDesigner OUT). Returns
 * `{"ok":true,"msg":{key,wire,attachment,qos}}` | `{"ok":false,"diags":[...]}`. Free with `sahou_free`.
 *
 * # Safety
 * `handle` is a live runtime; `node`/`conn`/`payload_json` are valid NUL-terminated C strings.
 */
char *sahou_prepare_publish(SahouRuntime *handle,
                            const char *node,
                            const char *conn,
                            const char *payload_json,
                            uint64_t seq);
#endif

#if defined(SAHOU_CAPI)
/**
 * pub_sub receive boundary (TouchDesigner IN). `wire` = the payload bytes; `attachment` = the
 * 16-hex per-connection hash (or null); `trusted` = a sender_hash already accepted (or null).
 * Returns tagged AcceptOutcome JSON. Free with `sahou_free`.
 *
 * # Safety
 * `handle` is a live runtime; `node`/`conn` are valid C strings; `attachment`/`trusted` are null
 * or valid C strings; `wire` points to `wire_len` readable bytes (or is null with `wire_len` 0).
 */
char *sahou_accept_sample(SahouRuntime *handle,
                          const char *node,
                          const char *conn,
                          const uint8_t *wire,
                          uintptr_t wire_len,
                          const char *attachment,
                          uint64_t seq,
                          const char *trusted);
#endif

#endif  /* SAHOU_H */
