//! sahou reference — print a concise reference to stdout so that AI (coding agents)
//! can safely edit schema.sahou.yaml.
//!
//! Two tests guarantee it does not drift from the core (sahou-core):
//! - Every `TypeName` variant name appears in the reference body (an exhaustive match
//!   breaks compilation when a variant is added, forcing this file to be updated).
//! - The canonical example embedded in the body passes `parse_contract` and produces
//!   zero `validate_schema` diagnostics (pinned by a test; upholds spec constraints ①②).

/// The annotated canonical example (few-shot) embedded in the reference.
/// Includes pub_sub + query + typed record (all of the int/float/bool/string/bytes/timestamp/enum/
/// array/map/group/union types). A test pins that it passes `parse_contract`.
pub const EXAMPLE_SCHEMA: &str = r#"schema: stage_demo
version: 1
nodes:
  sensor: { kind: sahou }            # the default when kind is omitted is sahou (a sahou-contract speaker)
  visuals: { kind: sahou }
  archive: { kind: sahou }
  legacy_console: { kind: external }  # a non-sahou device. Can be a wiring target but does not speak the contract
connections:
  # pattern: pub_sub — one-to-many distribution. The only slot is payload
  touch:
    pattern: pub_sub
    from: sensor
    to: [visuals, archive]           # to accepts only identifiers already defined in nodes, and cannot equal from
    reliability: reliable            # the default is best_effort (drops allowed). Guaranteed delivery is explicit opt-in
    congestion: block                # the default is drop (discard under congestion)
    payload:
      typing: typed                  # setting any means unvalidated (no type safety; the GUI marks it red)
      fields:
        - { name: x, type: float, min: 0, max: 1 }
        - { name: active, type: bool }
        - { name: phase, type: enum, values: [down, move, up] }
        - name: meta
          type: group                # anonymous inline hierarchy (the alternative to named nesting)
          fields:
            - { name: ts, type: timestamp }              # integer epoch milliseconds
            - { name: thumb, type: bytes, required: false }  # a base64 string on the wire
            - { name: note, type: string, required: false, max_len: 120 }
  points:
    pattern: pub_sub
    from: sensor
    to: [visuals]
    payload:
      typing: typed
      fields:
        # array/map cannot omit items (the element/value type). array can nest (point cloud = array<array<float>>)
        - { name: pts, type: array, items: { type: array, items: float } }
        - { name: tags, type: map, items: string }
        - { name: extra, type: union, any_of: [int, string] }  # untagged: accepted if it matches any option
  # pattern: query — one-to-one request/response. The slots are request + response
  get_level:
    pattern: query
    from: sensor
    to: [archive]
    selector: latest                 # query only (attaching it to pub_sub is rejected with unexpected_selector)
    request:
      typing: typed
      fields:
        - { name: sel, type: string, max_len: 64 }
    response:
      typing: typed
      fields:
        - { name: level, type: int }
  # raw data with no type validation (video etc.) uses kind: opaque
  raw_video:
    pattern: pub_sub
    from: legacy_console
    to: [visuals]
    payload: { typing: any, kind: opaque, encoding: "video/raw" }
"#;

/// The body of `sahou reference` (printed to stdout verbatim).
pub fn reference_text() -> String {
    format!(
        r#"# Sahou schema authoring reference (for AI)

## 1. What Sahou is

Sahou is a schema-first communication layer for production environments. You describe the shape of
the communication (types and wiring) in a single contract, `schema.sahou.yaml`, and the core (Rust)
parses / validates / codegens it. Not as heavy as gRPC, and not as loosely typed as OSC.

**Three-file separation** (do not conflate them):
- `schema.sahou.yaml` — the contract (meaning, types, wiring). **The single source to edit.** Edited by humans/AI/GUI.
- `endpoints.<env>.yaml` — deployment (per-environment connection settings). A separate file from the contract. Empty by default.
- `layout.sahou.json` — GUI coordinates only. Has no bearing on the contract's meaning.

Everything under `gen/` is generated by `sahou gen` (IR / type stubs). Do not edit by hand.

## 2. The schema.sahou.yaml format

Top level: `schema` (required; also the namespace) / `version` (default "1") /
`nodes` (required; may be an empty map) / `connections` (required; may be an empty map).

### Node

```yaml
<node_id>: {{ kind: sahou }}   # or kind: external
```
- `kind: sahou` — a device/process that speaks the sahou contract (default).
- `kind: external` — a non-sahou device. Can be a wiring target (to) but does not speak the contract.

### Connection

```yaml
<connection_id>:
  pattern: pub_sub | query    # <- determines the shape of the slots
  from: <node_id>
  to: [<node_id>, ...]        # a single value may be a bare string. Must be defined in nodes and not equal to from
  key: <keyexpr override>     # when omitted, auto-derived from namespace + connection id
  selector: <string>          # pattern: query only (cannot be attached to pub_sub)
  reliability: best_effort | reliable   # default best_effort
  congestion: drop | block               # default drop
  priority: realtime | interactive_high | interactive_low | data_high | data | data_low | background  # default data
  express: true | false        # default false
  encoding: json               # the connection's encoding (a contract attribute). Currently json only; default json
  validate: full | sampled | off  # validation level (default full)
  # slots that pattern determines:
  payload: <Slot>    # pattern: pub_sub only
  request: <Slot>    # pattern: query only
  response: <Slot>   # pattern: query only
```

### Slot

```yaml
typing: any | typed   # any = unvalidated (the GUI marks it red; no type safety)
kind: record | opaque # default record. opaque is raw data (has no fields)
fields: [<Field>, ...] # kind: record only
encoding: <string>      # free-form text for kind: opaque (e.g. "video/raw")
```

### Field (type is one of the following 11)

```yaml
name: <string>
type: int | float | bool | string | bytes | timestamp | enum | array | map | group | union
required: true | false   # default true
default: <value>          # rejected with invalid_default if it does not match the type/constraints
# type-specific attributes:
min: <number>             # int/float
max: <number>             # int/float
max_len: <uint>           # string
values: [<string>, ...]   # enum (empty is rejected)
items: <TypeSpec>         # array/map (omitting it is rejected). The array element type, or the map value type
any_of: [<TypeSpec>, ...] # union (omitting/empty is rejected; untagged = accepted if it matches any)
fields: [<Field>, ...]    # group (anonymous inline hierarchy)
```

Type notes:
- `int` / `float` — `min`/`max`. int->float is a compatible type promotion.
- `bool` — booleans only.
- `string` — `max_len` sets the character-count limit.
- `bytes` — a base64 string on the wire (JSON).
- `timestamp` — an **integer** of epoch milliseconds (a non-integer is type_mismatch).
- `enum` — `values` required (empty is rejected with empty_enum).
- `array` — `items` required (omitting it is rejected with missing_items). Can nest (`array<array<float>>` for point clouds etc.).
- `map` — `items` required (the value type; omitting it is rejected with missing_items).
- `group` — anonymous inline hierarchy (the alternative to named nesting).
- `union` — `any_of` required (empty is rejected with empty_union). untagged: accepted if it matches any candidate type.

## 3. Non-negotiable invariants (points AI tends to break)

- Do not mix contract (schema) <-> deployment (endpoints) <-> coordinates (layout). Do not write deployment or coordinates in the contract file.
- **pattern determines the shape of the slots**: pub_sub -> `payload` only / query -> `request`+`response` only.
  Doing the opposite is rejected with missing_slot / unexpected_slot.
- `to` accepts only valid targets (defined in `nodes`). A self-loop equal to `from` is forbidden.
- Duplicate keys and unknown keys (typos) are rejected at the boundary (not silently collapsed). serde's defaults of
  "duplicate = last-wins" and "unknown = drop" are eliminated via `deny_unknown_fields` / unique-map checks.
- `typing: any` is unvalidated (do not use it for fields whose type you want guaranteed; the GUI marks it red).
- `selector` is `pattern: query` only (attaching it to pub_sub is rejected with unexpected_selector).

## 4. Diagnostic codes (the `{{code, path, message}}` that `sahou validate` returns)

| code | meaning |
|---|---|
| `parse_error` | a parse-stage rejection such as YAML syntax / type mismatch / duplicate key / unknown key (typo) |
| `unknown_node` | `from`/`to` points at an identifier not in `nodes` |
| `self_loop` | `from` and `to` are the same node |
| `missing_slot` | a slot required by the pattern is missing (pub_sub=payload / query=request+response) |
| `unexpected_slot` | a slot the pattern cannot have is present |
| `unexpected_selector` | `selector` is attached to a `pattern: pub_sub` |
| `duplicate_field` | a field name is duplicated within the same Slot |
| `non_finite_bound` | `min`/`max` is set to NaN/Inf |
| `invalid_range` | `min > max` |
| `empty_enum` | `type: enum` but `values` is empty |
| `missing_items` | `items` is omitted for `array`/`map` |
| `empty_union` | `type: union` but `any_of` is empty |
| `invalid_default` | the `default` value does not match its own type/constraints (min/max/values etc.) |

## 5. The edit loop (most important)

1. Edit `schema.sahou.yaml`.
2. Run `sahou validate <file>`.
3. Fix each returned diagnostic `{{code, path, message}}` at the location given by its `path` (look up what the code means in the table above).
4. Repeat 1-3 until there are zero rejections.
5. If `sahou gui` is open, file edits are reflected in the GUI immediately.

## 6. Canonical example (pub_sub + query + typed record, including all types)

```yaml
{EXAMPLE_SCHEMA}```

## 7. Implementing an app (runtime)

Editing the contract is only half the job. To write an app that speaks it, use the runtime library plus
the generated stub — never hand-roll transport or validation (the core returns the boundary NO):

- **TypeScript** — `sahou` (`npm i sahou`; browser entry `sahou/browser`).
- **Python** — `sahou` (`pip install sahou`).

Steps:
1. `sahou gen --lang <ts|python> --node <name>` writes a typed stub under `gen/<name>/` (types only; the engine never reads it).
2. Connect with the runtime, then wrap it with the stub's `typedNode` / `typed_node` for typed calls:
   - TS: `const node = typedNode(await connect("gen/descriptor.json", {{ node: "<name>" }}));`
   - Python: `node = typed_node(sahou.connect("gen/descriptor.json", node="<name>"))`
3. API: `publish` / `subscribe` / `queryConfirmed` (TS) or `query_confirmed` (py) / `answer` / `close`.
   A send-boundary NO throws `SahouRejected`; a subscribe-boundary NO goes to `onReject` (never the handler).
"#,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use sahou_core::parse::parse_contract;
    use sahou_core::schema_check::validate_schema;
    use sahou_core::typespec::TypeName;

    /// The **single source of truth** for the drift-guard. The only exhaustive match that maps every
    /// TypeName variant to "(display name, successor variant)". With no wildcard, adding a variant to
    /// TypeName makes this match non-exhaustive and fails compilation (= the single point that forces an update).
    ///
    /// It returns the "successor" because `all_type_names()` uses this match as its origin to **enumerate**
    /// all variants. There is no separate array for enumeration (a separate one could not detect a missing addition).
    /// Return value: (display name, this variant's next variant / None if it is the last).
    fn name_and_successor(t: TypeName) -> (&'static str, Option<TypeName>) {
        match t {
            TypeName::Int => ("int", Some(TypeName::Float)),
            TypeName::Float => ("float", Some(TypeName::Bool)),
            TypeName::Bool => ("bool", Some(TypeName::String)),
            TypeName::String => ("string", Some(TypeName::Bytes)),
            TypeName::Bytes => ("bytes", Some(TypeName::Timestamp)),
            TypeName::Timestamp => ("timestamp", Some(TypeName::Enum)),
            TypeName::Enum => ("enum", Some(TypeName::Array)),
            TypeName::Array => ("array", Some(TypeName::Map)),
            TypeName::Map => ("map", Some(TypeName::Group)),
            TypeName::Group => ("group", Some(TypeName::Union)),
            TypeName::Union => ("union", None),
        }
    }

    /// Enumerate (name, TypeName) for every variant by following successors from the first (Int).
    /// The only generator is the exhaustive match in `name_and_successor`.
    fn all_type_names() -> Vec<(&'static str, TypeName)> {
        let mut out = Vec::new();
        let mut cur = Some(TypeName::Int);
        while let Some(t) = cur {
            let (name, next) = name_and_successor(t);
            out.push((name, t));
            cur = next;
        }
        out
    }

    #[test]
    fn reference_mentions_all_typename_variants() {
        let text = reference_text();
        let all = all_type_names();
        // Soundness of the successor chain: every variant is enumerated exactly once
        // (a safeguard so the coverage check below does not break if a new variant is not inserted into the chain correctly).
        let mut seen: Vec<&str> = Vec::new();
        for (name, _) in &all {
            assert!(
                !seen.contains(name),
                "the successor chain visited variant '{name}' twice (miswiring in name_and_successor)"
            );
            seen.push(name);
        }
        for (name, _) in &all {
            assert!(
                text.contains(name),
                "the reference does not mention type '{name}' (TypeName drift)"
            );
        }
    }

    #[test]
    fn example_schema_parses_and_validates_clean() {
        let contract =
            parse_contract(EXAMPLE_SCHEMA).expect("the canonical example passes parse_contract");
        let diags = validate_schema(&contract);
        assert!(
            diags.is_empty(),
            "the canonical example should produce zero validate_schema diagnostics: {diags:?}"
        );
    }

    #[test]
    fn reference_mentions_main_diagnostic_codes() {
        let text = reference_text();
        const CODES: &[&str] = &[
            "parse_error",
            "unknown_node",
            "self_loop",
            "missing_slot",
            "unexpected_slot",
            "unexpected_selector",
            "duplicate_field",
            "non_finite_bound",
            "invalid_range",
            "empty_enum",
            "missing_items",
            "empty_union",
            "invalid_default",
        ];
        for code in CODES {
            assert!(
                text.contains(code),
                "the reference does not mention diagnostic code '{code}'"
            );
        }
    }

    #[test]
    fn reference_mentions_three_file_separation() {
        let text = reference_text();
        for name in [
            "schema.sahou.yaml",
            "endpoints.<env>.yaml",
            "layout.sahou.json",
        ] {
            assert!(
                text.contains(name),
                "the reference does not mention '{name}'"
            );
        }
    }

    #[test]
    fn reference_mentions_runtime_implementation() {
        // Beyond authoring the contract, the reference must tell AI how to implement an app:
        // which runtime library to use and the connect/publish/subscribe API.
        let text = reference_text();
        for needle in [
            "sahou",
            "pip install sahou",
            "connect(",
            "publish",
            "subscribe",
            "queryConfirmed",
        ] {
            assert!(
                text.contains(needle),
                "the reference does not mention runtime impl: '{needle}'"
            );
        }
    }
}
